### ISSUE TITLE
Add grunt

### ISSUE THREAD

**Issue by starcalibre** [microscopium/microscopium-ui#1]
Add grunt with (at least) the following plugins:
* Karma - unit testing
* JSLint - code quality checking
* Watch - re-run server whenever changes made to file (very cool!)

**Comment by jni** [comment]
This is resolved, right?

**Comment by starcalibre** [comment]
Yes, though we don't have any unit tests yet.

**Comment by jni** [comment]
That's a separate issue. Closing this! =)
