### ISSUE TITLE
Allow filtering of dataset using a list of GeneIDs

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium-ui#14]
To push #13 a bit further, some biologists may want to look at what their favourite genes are doing on the chart. I envision a text box in which a researcher can paste a list of gene names separated by spaces, tabs, commas, newlines, or some combination thereof, and those genes would be somehow highlighted on the plot. (A small output text box would display warnings for gene IDs not found.) The highlighting would persist as long as the text box was not cleared.

Both #13 and this issue relate to actual questions from the Marcelle team.

**Comment by starcalibre** [comment]
This, along with filtering on rows and columns should absolutely be added. This can either be implemented using crossfilter (if we want to filter data in the browser), or using Mongo queries.

I think we should add the filters in a slide-out window (see http://blog.themearmada.com/demos/off-canvas-menu/ for an example) to conserve on screen real estate.

**Comment by jni** [comment]
Ooh yes I do like the off-canvas menu idea! =) Is it easy to stick a text box in there? Also, there should be an indicator on the menu icon when filtering is active, so that someone who turns it on and forgets doesn't sit there wondering wtf is wrong with his plot that it's missing umpteen samples. =)

**Comment by starcalibre** [comment]
Yeah, a textbox is just a HTML element.. that's no problem. 

That'd be cool.. the icon you click to bring up the filter menu could change colour according to filtering being active or not!

**Comment by starcalibre** [comment]
This feature was added in #40
