### ISSUE TITLE
Add React.js framework

### ISSUE THREAD

**Issue by starcalibre** [microscopium/microscopium-ui#17]
[React.js](http://facebook.github.io/react/) is a framework written by the Facebook team that's built for pages where lots of DOM manipulation happens (ie our UI). Two reasons I want to use it:

* React uses a 'virtual DOM' model.. DOM changes are calculated in memory (as opposed to in the browser), and a diff is applied to the DOM. So you're only changing the DOM when you need to. Given the insane amounts of DOM manipulation we're doing with D3, this will be of great benefit to us.
* Each part of the interface is compartmentalised into 'components' that have uniform methods to handle state changes, initialisation, etc. This will make code much more modular and thus easier to maintain and test.

[Here's](http://nicolashery.com/integrating-d3js-visualizations-in-a-react-app/) a great blog-post detailing how D3 plots can be cast as React components. I think the code looks much nicer this way, and if we're getting significant performance gains.. it's a no-brainer!

**Comment by jni** [comment]
:+1: ! Looks awesome! =)

**Comment by starcalibre** [comment]
We've done well without a framework so far, so I'm closing this off.
