### ISSUE TITLE
Use jQuery to generate image gallery

### ISSUE THREAD

**Issue by starcalibre** [microscopium/microscopium-ui#18]
When rendering the nearest neighbours image gallery, jQuery (or some other method) should be used to generate the containers for the image. This will prevent a bunch of a repeated HTML, and allow us to display galleries of varying sizes.

**Comment by jni** [comment]
LOL Is this you giving up on the second-to-last point of #12? LOL

**Comment by starcalibre** [comment]
Yes, for now.. it's lots of hideous jQuery and I think React might offer a better way of doing it !

**Comment by starcalibre** [comment]
The HTML for the image gallery is generated using serverside templating now #75
