### ISSUE TITLE
Add complete public dataset to web demo

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium-ui#28]
@starcalibre had the excellent idea of finding a dataset that can be made public on microscopium.io, which now points to a VM that we own on the nectar research cloud. 

@VCFG do you have or know of any datasets that would be suitable for public consumption?

**Comment by starcalibre** [comment]
http://play.microscopium.io!!! Is there any reason to keep this one open?

**Comment by jni** [comment]
BOOM! No there isn't! Awesome work, team! =D I'm really excited about this.
