### ISSUE TITLE
Overlay screen single-z-score result onto the neighbour plot

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium-ui#39]
Every screen we get has a z-score result, or a list of hits. It would be great to be able to see these on the neighbour plot / dimension-reduced scatterplot.

**Comment by starcalibre** [comment]
It seems like there's a few different values that could be overlayed onto the scatterplot.. z-score/hits, viability, a PCA value, etc. I suggest adding a radio button menu that will change the colouring of the points according to the chosen option. The radio buttons could be generated according to what data is available for the screen.

**Comment by jni** [comment]
I think at this point I want to simplify before we go wild on the options. So, let's assume z-score initially, and add other options as users request them.

**Comment by jni** [comment]
Use a colormap to display the value. Matplotlib's new [viridis colormap](http://bids.github.io/colormap/) has been implemented in D3 (see links in above page). I suggest we use that. (A light-gray background might be needed for that, though.)

**Comment by starcalibre** [comment]
Here's a a few [examples](http://bl.ocks.org/starcalibre/6cccfa843ed254aa0a0d) of some colour scales -- I think viridis looks good, even without a light gray background.

Here's how I think I should add this..

Add a new field to the ``Sample`` document, call it ``available_overlays``. In this field store an array an strings of which information is available for the screen. Some screens have nothing, while other's like Keefe's are multi-parametric so there's a few different scores to overlay. The contents of this array are used to generate the drop-down menu to change which number is used to generate the colour scale. If there's no additional information for the overlays, the dropdown menu will be empty or won't render at all.

Each sample then has the scores saved in an object, ``overlays``. So let's say I have two scores.. ``z_score`` and ``viability``. The ``Screen`` document will contain two strings ``z_score`` and ``viability``. The ``Sample`` document field object will be ``{ z_score: -1.45, viability: 2.3 }``.

**Comment by jni** [comment]
Hey,

I love both viridis and PuOr! I think it does depend on the application whether one prefers a diverging or a single colorscale, so make it at least configurable at start-up time.

Your implementation idea sounds reasonable. Do you think it would be worthwhile to add a column-wise version of the storage for these attributes? It might affect performance quite dramatically.

**Comment by starcalibre** [comment]
It could even be configurable during run time, as per the example I just posted! :)

As long as the order of the ``Sample`` documents in the array delivered from Mongo is guaranteed to match the order of column-wise storage, that can be done. I'm not sure what the performance benefit would be, if any.

**Comment by starcalibre** [comment]
Feature added in #78
