### ISSUE TITLE
Performance of filtering is sluggish

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium-ui#42]
Clicking around with no filters active is nice and smooth. Once a filter is active, everything becomes much more stuttery. We should explore ways to make the experience smooth.

**Comment by jni** [comment]
As mentioned in #40, a quick thing to try might be to replace transparency with just a very light blue colour, see if that improves things.

**Comment by jni** [comment]
Update: #43 fixes this for Chrome, and improves things in other browsers.

**Comment by starcalibre** [comment]
Filtering is now quite fast with canvas scatterplot added in #77, any slowdown was in the SVG rather than the speed of Lodash filtering the data.
