### ISSUE TITLE
Add back and forwards functionality

### ISSUE THREAD

**Issue by starcalibre** [microscopium/microscopium-ui#53]
This should be fairly easy to implement, it's just a matter of keeping a record of each sample id that has been visited. The back and forward arrows could be added to the top navbar using the FontAwesome [left](http://fortawesome.github.io/Font-Awesome/icon/chevron-left/) and [right](http://fortawesome.github.io/Font-Awesome/icon/chevron-right/) chevron arrows.

**Comment by jni** [comment]
Not sure chevron says back as much as other arrow types...

**Comment by starcalibre** [comment]
Feature added in #61
